### ISSUE TITLE
Config FFmpegLocation already set by TimedMediaHandler

### ISSUE THREAD

**Issue by FlorianSW** [HydraWiki/mediawiki-embedvideo#105]
The config option `FFmpegLocation` is already defined in [TimedMediaHandler](https://github.com/wikimedia/mediawiki-extensions-TimedMediaHandler/blob/e25bd44c86b68b3503f5f94897507cbb88b85860/extension.json#L238) and can therefore not be set again by the EmbedVideo extension (or vice versa). This results in the following exception being thrown when both extensions are installed:
```
PHP Fatal error:  Uncaught RuntimeException: The configuration setting 'wgFFmpegLocation' was already set by MediaWiki core or another extension, and cannot be set again by EmbedVideo. in /data/deployment/staging/main/includes/registration/ExtensionProcessor.php:520
Stack trace:
#0 /data/deployment/staging/main/includes/registration/ExtensionProcessor.php(473): ExtensionProcessor->addConfigGlobal('wgFFmpegLocatio...', '/usr/bin/ffmpeg', 'EmbedVideo')
#1 /data/deployment/staging/main/includes/registration/ExtensionProcessor.php(224): ExtensionProcessor->extractConfig1(Array)
#2 /data/deployment/staging/main/includes/registration/ExtensionRegistry.php(265): ExtensionProcessor->extractInfo('/data/deploymen...', Array, 1)
#3 /data/deployment/staging/main/includes/registration/ExtensionRegistry.php(159): ExtensionRegistry->readFromQueue(Array)
#4 /data/deployment/staging/main/includes/Setup.php(122): ExtensionRegistry->loadFromQueue()
#5 /data/deployment/staging/main/maintenance/doMaintenance.php(81): require_once('/data/deploymen. in /data/deployment/staging/main/includes/registration/ExtensionProcessor.php on line 520
```

**Comment by Alexia** [comment]
EmbedVideo is intended to replace TimedMediaHandler as the wiki's default media handler when used in [[File:Example.mp3]] tags.  They are going to clash regardless if the configuration setting is changed.

**Comment by FlorianSW** [comment]
That may be the case, however, the config option is not used in the code base, if I see it correctly. Also: The use case of why I've the extension installed is not to handle video/music files but rather embedding youtube (and other services) videos.

**Comment by AhmadFCheema** [comment]
Any update on this?
Probably more users would start running into this error as they upgrade to REL1_32 of [Extension:TimedMediaHandler](https://www.mediawiki.org/wiki/Extension:TimedMediaHandler) with MediaWiki core 1.32.
